export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LIKE_COMMENT = 'LIKE_COMMENT'
export const SET_SIDEBAR_POSTS = 'SET_SIDEBAR_POSTS';
export const SET_POST_COMMENTS = 'SET_POST_COMMENTS';
export const CREATE_POST = 'CREATE_POST';

export const COMMENT_PER_PAGE = 10;